name       : gegl
version    : 0.2.0
release    : 18
source     :
    - https://download.gimp.org/pub/gegl/0.2/gegl-0.2.0.tar.bz2 : df2e6a0d9499afcbc4f9029c18d9d1e0dd5e8710a75e17c9b1d9a6480dd8d426
license    :
    - GPL-3.0-only
    - LGPL-3.0-only
component  : multimedia.graphics
summary    : GEGL (Generic Graphics Library) is a graph based image processing framework
description: |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(exiv2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libavfilter)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(pangocairo)
    - pkgconfig(sdl2)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2012-4433.patch
    %patch -p1 < $pkgfiles/ffmpeg.patch
    %configure --disable-static --with-vala
build      : |
    %make
install    : |
    %make_install
