name       : gegl
version    : 0.4.14
release    : 30
source     :
    - https://download.gimp.org/pub/gegl/0.4/gegl-0.4.14.tar.bz2 : 4c01d58599d8ddb3714effd2675ea1863272cf2d7d9ed3d32aee80c89f859901
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : GEGL (Generic Graphics Library) is a graph based image processing framework
description: |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
replaces   :
    - gegl3
    - devel : gegl3-devel
    - docs : gegl3-docs
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(exiv2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(jasper)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libavfilter)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(pangocairo)
    - pkgconfig(sdl2)
    - vala
setup      : |
    %configure --disable-static --with-vala
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
