name       : gegl
version    : 0.4.38
release    : 54
source     :
    - https://download.gimp.org/pub/gegl/0.4/gegl-0.4.38.tar.xz : e4a33c8430a5042fba8439b595348e71870f0d95fbf885ff553f9020c1bed750
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : GEGL (Generic Graphics Library) is a graph based image processing framework
description: |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
replaces   :
    - gegl3
    - devel : gegl3-devel
    - docs : gegl3-docs
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(babl)
    - pkgconfig(exiv2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(jasper)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libavfilter)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(luajit)
    - pkgconfig(pangocairo)
    - pkgconfig(sdl2)
    - vala
setup      : |
    %meson_configure -Dgtk-doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
