name       : gegl
version    : 0.4.22
release    : 39
source     :
    - https://gitlab.gnome.org/GNOME/gegl/-/archive/GEGL_0_4_22/gegl-GEGL_0_4_22.tar.bz2 : 07e78de7ed9506703aff9be327a24414f9476cfdd8431c857b317e15121637f3
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : multimedia.graphics
libsplit   : no
summary    : GEGL (Generic Graphics Library) is a graph based image processing framework
description: |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
replaces   :
    - gegl3
    - devel : gegl3-devel
    - docs : gegl3-docs
builddeps  :
    - pkgconfig(babl)
    - pkgconfig(exiv2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(jasper)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libavfilter)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(libwebp)
    - pkgconfig(luajit)
    - pkgconfig(pangocairo)
    - pkgconfig(sdl2)
    - vala
setup      : |
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
