name        : gegl
version     : 0.3.0
release     : 5
source      :
    - http://download.gimp.org/pub/gegl/0.3/gegl-0.3.0.tar.bz2 : f0fec8f2e7b8835979d3cf4e38b05d41bb79f68dc80cf899a846484da693bbf7
homepage    : http://www.gegl.org/
license     :
    - GPL-3.0
summary     : GEGL (Generic Graphics Library) is a graph based image processing framework.
builddeps   :
    - pkgconfig(babl)
    - pkgconfig(libpng15)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libavfilter)
    - pkgconfig(sdl2)
    - pkgconfig(lcms2)
    - pkgconfig(libv4l2)
    - pkgconfig(exiv2)
    - pkgconfig(libwebp)
    - pkgconfig(gdk-pixbuf-2.0)
    - vala
    - libjpeg-turbo-devel
clang       : no
description : |
    GEGL provides infrastructure to do demand based cached non destructive image editing on larger than RAM buffers. Through babl it provides support for a wide range of color models and pixel storage formats for input and output.
setup      : |
    %configure --disable-static --with-vala
build      : |
    %make
install    : |
    %make_install
